project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"

website:
  title: "Statistical Modeling"
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - text: "Course materials"
        file: materials.qmd
      - text: "Code"
        file: code.qmd
      - text: "Online resources"
        file: resources.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: source

